config/routes.rb
Rails.application.routes.draw do
	resources :contacts, only: [:new, :create]
	resources :visitors, only: [:new, :create]
	root to: 'visitors#new'
end

app/models/contact.rb
class Contact
	include ActiveModel::Model
	attr_accessor :name, :string
	attr_accessor :email, :string
	attr_accessor :content, :string

	validates_presence_of :name
	validates_presence_of :email
	validates_presence_of :content
	validates_format_of :email,
		with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
	validates_length_of :content, :maximum => 500
end

app/models/owner.rb
class Owner

	def name
		name = 'Foobar Kadigan'
	end

	def birthdate
		birthdate = Date.new(1990, 12, 22)
	end

	def countdown
		Rails.logger.debug 'DEBUG: Entering in tthe countdown method'

		today = Date.today
		birthday = Date.new(today.year, birthdate.month, birthdate.day)
		if birthday > today
			countdown = (birthday - today).to_i
		else
			countdown = (birthday.next_year - today).to_i
		end
		Rails.logger.debug 'DEBUG: found countdown ' +countdown.to_s

	end
end

app/models/owner__removed.rb
class Owner

	def name
		name = 'Foobar Kadigan'
	end

	def birthdate
		birthdate = Date.new(1990, 12, 22)
	end

	def countdown
		Rails.logger.debug 'DEBUG: Entering in tthe countdown method'

		today = Date.today
		birthday = Date.new(today.year, birthdate.month, birthdate.day)
		if birthday > today
			countdown = (birthday - today).to_i
		else
			countdown = (birthday.next_year - today).to_i
		end
		Rails.logger.debug 'DEBUG: found countdown ' +countdown.to_s

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(secure_params)
		if @contact.valid?
			# TODO send message
			UserMailer.contact_email(@contact).deliver_now
			flash[:notice] = "Message sent from #{@contact.name}."
			redirect_to root_path
		else
			render :new
		end
	end

	private

	def secure_params
		params.require(:contact).permit(:name, :email, :content)
	end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/contacts_controller_example_usingRails_String_api_validation.rb
class ContactsController < ApplicationController
	def process_form
		Rails.logger.debug "DEBUG: params are #{params}"
		if params[:contact][:name].blank?
			raise 'Name is blank!'
		end
		if params[:contact][:email].blank?
			raise 'email is blank!'
		end
		if params[:contact][:content].blank?
			raise 'Message is blank!'
		end
		

		flash[:notice] = "Recieved request from #{params[:contact][:name]}"
		redirect_to root_path
	end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	def new
		@visitor = Visitor.new
	end

	def create
		@visitor = Visitor.new(secure_params)
		if @visitor.valid?
			flash[:notice] = "Signed up #{@visitor.email}."
			redirect_to root_path
		else
			render new
		end
	end

	private

	def secure_params
		params.require(:visitor).permit(:email)
	end
end

app/controllers/visitors_controller_orig.rb
class VisitorsController < ApplicationController
	def new
		##Rails.logger.debug 'DEBUG: entering new method'
		@owner = Owner.new
		##Rails.logger.debug 'DEBUG: Owner name is ' + @owner.name
		##raise 'deliberate Raise of a Problem'
		render 'visitors/new'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %>
<h3>Contact New method</h3>
<div class="form" >
	<%= simple_form_for @contact do |form| %>
		<%= form.error_notification %>
		<%= form.input :name, autofocus: true %>
		<%= form.input :email %>
		<%= form.input :content, as: :text %>
		<%= form.button :submit, 'Submit', class: 'submit' %>
	<% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application_with_sidebar.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="main">
		<%= yield %>
	</div>
	<div class="sidebar">
		<%= yield :sidebar %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3> About Foobar Kardigan</h3>
<p>He was born in somewhere , bal bla bla, </p>
<p>His favorite thing is:</p>
<p>Lorem ipsim dolor sit amet, consectetur adiposicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aligua. </p>

app/views/pages/contact_example1.html.erb
<% content_for :title do %>Contact<% end %>
<h3> Contact</h3>
<div class="form">
	<%= simple_form_for :contact, url: contact_path do |form| %>
		<%= form.input :name, autofocus: true %>
		<%= form.input :email %>
		<%= form.input :content, as: :text %>
		<%= form.button :submit, 'Submit', class: 'submit' %>
	<% end %>
</div>

app/views/visitors/new.html.erb
<% content_for :title do %>FoobarKadigan<% end %>
<% content_for :description do %>Website of Foobar Kadigan<% end %>
<section>
	<img src="http://lorempixel.com/1170/600/nightlife/1">
</section>
<div class="column">
	<h3>Stay in touch and travel with us</h3>
</div>
<div class="column">
	<div class="form-centered">
		<%= simple_form_for @visitor do |f| %>
			<%= f.error_notification %>
			<%= f.input :email, label: false, :placeholder => 'jl@lejoly.com' %>
			<br/>
			<%= f.button :submit, "sign up for the newsletter", :class => "submit" %>
		<% end%>
	</div>
</div>
</section>

app/views/visitors/new_initial_workingExample.html.erb
<h3>Home</h3>
<p>Welcome to the home of <%= @owner.name %>.</p>
<p>I was born on <%= @owner.birthdate %>.</p>
<p>Only <%= @owner.countdown %> days untill my birthday!</p>